apiVersion: v1
kind: ConfigMap
metadata:
  name: fulcrum-config
  labels:
    app: fulcrum
data:
  PORT: "8080"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: "user"
  DB_NAME: "fulcrum"
  STORE_POSTGRES: "true"
  STORE_NDJSON: "true"
  RATE_LIMIT: "100"
  CB_FAILURE_THRESHOLD: "5"
  CB_TIMEOUT: "10s"
