apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulcrum
  labels:
    app: fulcrum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulcrum
  template:
    metadata:
      labels:
        app: fulcrum
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: fulcrum
          image: ghcr.io/abkhan/ingestevent:v1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fulcrum-config
            - secretRef:
                name: fulcrum-secrets
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
